language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -U pip
  - pip install pybuilder
  - pyb install_dependencies
script:
  - pyb run_unit_tests -X
deploy:
  provider: pypi
  user: ingofruend
